# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hussein/Dev/compil/project/Optimizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hussein/Dev/compil/project/Optimizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hussein/Dev/compil/project/Optimizer/CMakeFiles /home/hussein/Dev/compil/project/Optimizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hussein/Dev/compil/project/Optimizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named optimizer

# Build rule for target.
optimizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optimizer
.PHONY : optimizer

# fast build rule for target.
optimizer/fast:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/build
.PHONY : optimizer/fast

src/lex.yy.o: src/lex.yy.c.o

.PHONY : src/lex.yy.o

# target to build an object file
src/lex.yy.c.o:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/lex.yy.c.o
.PHONY : src/lex.yy.c.o

src/lex.yy.i: src/lex.yy.c.i

.PHONY : src/lex.yy.i

# target to preprocess a source file
src/lex.yy.c.i:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/lex.yy.c.i
.PHONY : src/lex.yy.c.i

src/lex.yy.s: src/lex.yy.c.s

.PHONY : src/lex.yy.s

# target to generate assembly for a file
src/lex.yy.c.s:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/lex.yy.c.s
.PHONY : src/lex.yy.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/main.c.s
.PHONY : src/main.c.s

src/symbol.o: src/symbol.c.o

.PHONY : src/symbol.o

# target to build an object file
src/symbol.c.o:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/symbol.c.o
.PHONY : src/symbol.c.o

src/symbol.i: src/symbol.c.i

.PHONY : src/symbol.i

# target to preprocess a source file
src/symbol.c.i:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/symbol.c.i
.PHONY : src/symbol.c.i

src/symbol.s: src/symbol.c.s

.PHONY : src/symbol.s

# target to generate assembly for a file
src/symbol.c.s:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/symbol.c.s
.PHONY : src/symbol.c.s

src/y.tab.o: src/y.tab.c.o

.PHONY : src/y.tab.o

# target to build an object file
src/y.tab.c.o:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/y.tab.c.o
.PHONY : src/y.tab.c.o

src/y.tab.i: src/y.tab.c.i

.PHONY : src/y.tab.i

# target to preprocess a source file
src/y.tab.c.i:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/y.tab.c.i
.PHONY : src/y.tab.c.i

src/y.tab.s: src/y.tab.c.s

.PHONY : src/y.tab.s

# target to generate assembly for a file
src/y.tab.c.s:
	$(MAKE) -f CMakeFiles/optimizer.dir/build.make CMakeFiles/optimizer.dir/src/y.tab.c.s
.PHONY : src/y.tab.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... optimizer"
	@echo "... edit_cache"
	@echo "... src/lex.yy.o"
	@echo "... src/lex.yy.i"
	@echo "... src/lex.yy.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/symbol.o"
	@echo "... src/symbol.i"
	@echo "... src/symbol.s"
	@echo "... src/y.tab.o"
	@echo "... src/y.tab.i"
	@echo "... src/y.tab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

